import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import Providers from "./providers/provider";

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '700']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Providers>
        <div className="flex h-screen">
            <Sidebar />
            {children}
        </div>
        </Providers>
      </body>
    </html>
  );
}
